# Generated by Django 2.2 on 2023-09-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctors',
            table='Doctor',
        ),
    ]
