# Generated by Django 2.2 on 2023-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('qualifications', models.TextField()),
                ('availability', models.TextField()),
                ('experience', models.PositiveIntegerField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
