# Generated by Django 2.2 on 2023-09-11 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='sex',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
