# Generated by Django 2.2 on 2023-09-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0003_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentt',
            name='Doctor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Management_System.Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='appointments',
            field=models.ManyToManyField(through='Management_System.appointmentt', to='Management_System.Doctor'),
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
