# Generated by Django 2.2 on 2023-09-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0005_auto_20230912_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
