# Generated by Django 2.2 on 2023-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0006_auto_20230912_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
