# Generated by Django 2.2 on 2023-09-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0007_auto_20230923_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='userd',
        ),
    ]
