# Generated by Django 2.2 on 2023-09-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0007_auto_20230912_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
