# Generated by Django 2.2 on 2023-09-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0008_auto_20230913_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
    ]
