# Generated by Django 2.2 on 2023-09-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0010_doctor_userd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doc',
        ),
    ]
