# Generated by Django 2.2 on 2023-09-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0011_remove_doctor_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management_System.Department'),
        ),
    ]
