# Generated by Django 2.2 on 2023-09-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0011_auto_20230913_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='payment_history',
        ),
    ]
