# Generated by Django 2.2 on 2023-09-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0012_remove_patient_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='payment_history',
            field=models.BooleanField(default=False),
        ),
    ]
