# Generated by Django 2.2 on 2023-09-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0013_patient_payment_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_history',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='drugs',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='tobbaco_history',
        ),
        migrations.AddField(
            model_name='medical_history',
            name='med_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='medical_files',
            field=models.FileField(null=True, upload_to='Document/'),
        ),
    ]
