# Generated by Django 2.2 on 2023-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0013_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='navpane',
            name='worker_role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
