# Generated by Django 2.2 on 2023-09-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0014_auto_20230913_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='your_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
