# Generated by Django 2.2 on 2023-09-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0015_auto_20230915_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='appointments',
        ),
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
