# Generated by Django 2.2 on 2023-09-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0017_remove_medical_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_history',
            name='userss',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Management_System.Patient'),
        ),
    ]
