# Generated by Django 2.2 on 2023-09-15 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0017_auto_20230915_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='your_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
