# Generated by Django 2.2 on 2023-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0018_auto_20230915_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_history',
            old_name='med_details',
            new_name='allergies',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='medical_files',
        ),
        migrations.AddField(
            model_name='medical_history',
            name='alcohol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='drugs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='emergency_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='emergency_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='med_condition',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='medication',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='symptoms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='tobbaco_history',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
