# Generated by Django 2.2 on 2023-09-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0019_auto_20230916_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approval_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='approval_receiptionist',
            field=models.BooleanField(default=False),
        ),
    ]
