# Generated by Django 2.2 on 2023-09-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0020_auto_20230916_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_files',
            field=models.FileField(null=True, upload_to='Document/'),
        ),
    ]
