# Generated by Django 2.2 on 2023-09-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0021_appointment_medical_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
