# Generated by Django 2.2 on 2023-09-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0022_auto_20230918_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
    ]
