# Generated by Django 2.2 on 2023-09-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0024_auto_20230918_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='doc',
        ),
    ]
