# Generated by Django 2.2 on 2023-09-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0026_doctor_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reasons',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management_System.Department'),
        ),
    ]
