# Generated by Django 2.2 on 2023-09-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0027_auto_20230920_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management_System.Department'),
        ),
    ]
