# Generated by Django 2.2 on 2023-09-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0028_auto_20230924_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medical_History',
        ),
    ]
