# Generated by Django 2.2 on 2023-09-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0028_auto_20230920_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management_System.Department'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('dosage', models.TextField()),
                ('patient_prs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management_System.appointment')),
            ],
        ),
    ]
