# Generated by Django 2.2 on 2023-09-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0033_auto_20230924_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentt',
            name='symptoms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
