# Generated by Django 2.2 on 2023-09-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0034_appointmentt_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='Report_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Status',
            field=models.TextField(null=True),
        ),
    ]
