# Generated by Django 2.2 on 2023-09-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0035_auto_20230925_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient_prs',
        ),
    ]
