# Generated by Django 2.2 on 2023-09-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0036_remove_prescription_patient_prs'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient_f',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Management_System.appointmentt'),
        ),
    ]
