# Generated by Django 2.2 on 2023-09-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0038_navpane_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navpane',
            options={'ordering': ['order']},
        ),
    ]
