# Generated by Django 2.2 on 2023-09-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management_System', '0041_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
    ]
